Repository itu-auv/auv-software, pull requests merged in 2025-06, with the labels that each got.

#213 Refactor align frame controller
  auv_control/auv_control/scripts/align_frame_controller.py
Labels: sim test succeeded, codex

#229 Fix the pressure_odom error
  auv_navigation/auv_localization/scripts/pressure_odometry_node.py
Labels: fix

#202 Use the timestamp from the IMU message instead of now
  auv_navigation/auv_localization/scripts/imu_odometry_node.py
Labels: hardware test succeeded

#224 Update altitude subscription to use odom_pressure
  auv_navigation/auv_mapping/launch/start.launch
  auv_vision/auv_detection/scripts/camera_detection_pose_estimator.py
Labels: needs hardware test
