Repository itu-auv/auv-software, pull requests merged in 2025-04, with the labels that each got.

#174 Fix and improve covariance handling in `imu_odometry_node`
  auv_navigation/auv_localization/scripts/imu_odometry_node.py
Labels: needs hardware test, hardware test succeeded

#161 Add EKF & Clustering to map node
  auv_navigation/auv_mapping/CMakeLists.txt
  auv_navigation/auv_mapping/include/auv_mapping/object_map_tf_server_ros.hpp
  auv_navigation/auv_mapping/include/auv_mapping/object_position_filter.hpp
  auv_navigation/auv_mapping/launch/start.launch
  auv_navigation/auv_mapping/src/object_map_tf_server_node.cpp
  auv_navigation/auv_mapping/src/object_map_tf_server_ros.cpp
  auv_navigation/auv_mapping/src/object_position_filter.cpp
  auv_smach/launch/start.launch
  auv_smach/src/auv_smach/common.py
  auv_smach/src/auv_smach/initialize.py
  auv_vision/auv_detection/CMakeLists.txt
  auv_vision/auv_detection/scripts/camera_detection_pose_estimator.py
Labels: enhancement, needs hardware test, needs simulation test

#146 Add taluy gui
  auv_teleop/CMakeLists.txt
  auv_teleop/images/itu_auv_workshop.jpg
  auv_teleop/launch/start_taluy_gui.launch
  auv_teleop/package.xml
  auv_teleop/scripts/dry_test_tab.py
  auv_teleop/scripts/services_tab.py
  auv_teleop/scripts/simulation_tab.py
  auv_teleop/scripts/taluy_gui.py
  auv_teleop/scripts/vehicle_control_tab.py
Labels: enhancement
