Repository itu-auv/auv-software, pull requests merged in 2025-07, with the labels that each got.

#260 Delete dvl to cam offset
  auv_vision/auv_detection/scripts/camera_detection_pose_estimator.py
Labels: needs hardware test

#254 fix odometry reset
  auv_control/auv_control/launch/start.launch
  auv_control/auv_control/scripts/reference_pose_publisher.py
Labels: needs hardware test, sim test succeeded

#245 GUI Additions
  auv_teleop/launch/start_taluy_gui.launch
  auv_teleop/scripts/dry_test_tab.py
  auv_teleop/scripts/services_tab.py
  auv_teleop/scripts/simulation_tab.py
  auv_teleop/scripts/taluy_gui.py
Labels: needs hardware test

#264 Create Torpedo Holes Frames
  auv_vision/auv_detection/scripts/camera_detection_pose_estimator.py
Labels: needs simulation test

#191 Add Roll State
  auv_navigation/auv_localization/launch/start.launch
  auv_navigation/auv_localization/scripts/dvl_odometry_node.py
  auv_smach/launch/start.launch
  auv_smach/scripts/main_state_machine.py
  auv_smach/src/auv_smach/gate.py
  auv_smach/src/auv_smach/initialize.py
  auv_smach/src/auv_smach/roll.py
  auv_teleop/scripts/simulation_tab.py
Labels: enhancement, hardware test succeeded
