Repository itu-auv/auv-software, pull requests merged in 2025-02, with the labels that each got.

#123 add birds eye camera to sim
  auv_sim/auv_sim_description/auv_sim_description/worlds/pool.world
Labels: sim test succeeded

#121 Add support for WrenchStamped
  auv_control/auv_control/include/auv_control/controller_ros.h
  auv_control/auv_control/include/auv_control/thruster_manager_ros.h
Labels: needs hardware test, hardware test succeeded

#61 feat: frame aware depth control
  auv_control/auv_control/include/auv_control/controller_ros.h
  auv_control/auv_control/scripts/reference_pose_publisher.py
  auv_msgs/srv/SetDepth.srv
Labels: needs hardware test, needs simulation test, hardware test succeeded

#122 teleop xbox controller
  auv_teleop/config/xbox.yaml
  auv_teleop/scripts/joy_manager.py
Labels: hardware test succeeded

#112 add: follow path action server (A, merge to main)
  auv_bringup/launch/start_navigation.launch
  auv_msgs/CMakeLists.txt
  auv_msgs/action/FollowPath.action
  auv_msgs/package.xml
  auv_navigation/auv_navigation/CMakeLists.txt
  auv_navigation/auv_navigation/launch/start.launch
  auv_navigation/auv_navigation/package.xml
  auv_navigation/auv_navigation/scripts/follow_path_action_server.py
  auv_navigation/auv_navigation/setup.py
  auv_navigation/auv_navigation/src/__init__.py
  auv_navigation/auv_navigation/src/auv_navigation/__init__.py
  auv_navigation/auv_navigation/src/auv_navigation/path_utils.py
Labels: needs hardware test

#91 Refactor and update gate trajectory logic and configurations
  auv_control/auv_control/CMakeLists.txt
  auv_control/auv_control/launch/start.launch
  auv_navigation/auv_mapping/CMakeLists.txt
  auv_navigation/auv_mapping/launch/start.launch
  auv_navigation/auv_mapping/scripts/gate_trajectory_publisher.py
  auv_navigation/auv_mapping/scripts/prop_transform_publisher.py
  auv_smach/src/auv_smach/gate.py
Labels: needs hardware test, needs simulation test, hardware test succeeded, sim test succeeded
